export const FETCH_CITIES = 'FETCH_CITIES';
export const RECEIVE_CITIES = 'RECEIVE_CITIES';
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const RECEIVE_RESTAURANTS = 'RECEIVE_RESTAURANTS';